name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start development setup
        run: |
          curl -o- https://raw.githubusercontent.com/leorodriguesf/dev-setup/refs/heads/main/boot | bash
